- name: create sealed-secret project
  k8s:
    name: sealed-secrets
    api_version: v1
    kind: Namespace
    state: present

- name: write sealed-secret key file
  copy:
    dest: "/tmp/sealed-secret-key.yaml"
    content: "{{ sealed_secret_key_file | b64decode }}"

- name: create sealed-secret 
  k8s:
    state: present
    src: "/tmp/sealed-secret-key.yaml"

- name: delete sealed-secret key file
  file:
    path: "/tmp/sealed-secret-key.yaml"
    state: absent
