- name: copy infra bill of materials
  copy:
    src: "{{ item }}"
    dest: "{{ playbook_workspace }}/repositories/gitops-0-bootstrap/{{ gitops_profile }}/"
    remote_src: yes
  with_items: "{{lookup('pipe', 'find {{ playbook_workspace }}/repositories/gitops-0-bootstrap/scripts/bom/ace/ -maxdepth 1 -mindepth 1 -type d').split() }}"

- name: push updated gitops-0-bootstrap repo
  shell:
    cmd: |
      git add .
      git commit -m "Deploy Cloud Pak ACE"
      git push origin
    chdir: "{{ playbook_workspace }}/repositories/gitops-0-bootstrap"

- name: deploy bootstrap argoapp
  community.kubernetes.k8s:
    state: present
    src: "{{ playbook_workspace }}/repositories/gitops-0-bootstrap/{{ gitops_profile }}/bootstrap.yaml"
    namespace: openshift-gitops
