- name: copy apps bill of materials
  copy:
    src: "{{ item }}"
    dest: "{{ playbook_workspace }}/repositories/gitops-0-bootstrap/{{ gitops_profile }}/"
    remote_src: yes
  with_items: "{{lookup('pipe', 'find {{ playbook_workspace }}/repositories/gitops-0-bootstrap/{{ gitops_recipe }}/ -maxdepth 1 -mindepth 1 -type d').split() }}"

- name: push updated gitops-0-bootstrap repo
  shell:
    cmd: |
      git add .
      git commit -m "Deploy GitOps Recipe {{ gitops_recipe }}"
      git push origin
    chdir: "{{ playbook_workspace }}/repositories/gitops-0-bootstrap"
