- name: update infrastructure items
  shell:
    cmd: |
      source ./scripts/infra-mod.sh 
    chdir: "{{ playbook_workspace }}/repositories/gitops-0-bootstrap"

- name: replace default storage class managed-nfs-storage with {{ ocs_rwx_storage_class }}
  shell:
    cmd: |
      find . -name '*.yaml' -print0 |
        while IFS= read -r -d '' File; do
          if grep -q "managed-nfs-storage" "$File"; then
            sed -i'.bak' -e "s#managed-nfs-storage#{{ ocs_rwx_storage_class }}#" $File
            rm "${File}.bak"
          fi
        done
    chdir: "{{ playbook_workspace }}/repositories/gitops-0-bootstrap"

- name: push updated gitops-0-bootstrap repo
  shell:
    cmd: |
      git add .
      git commit -m "update storage classes"
      git push origin
    chdir: "{{ playbook_workspace }}/repositories/gitops-0-bootstrap"
